name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      OPEN_MATEO_WEATHER_URL: ${{ vars.OPEN_MATEO_WEATHER_URL }}
      NODE_ENV: test
      PORT: 3000

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npx eslint .

    - name: Print environment variables
      run: printenv | grep -i 'MONGODB\|OPEN_MATEO'

    - name: Run Tests
      run: npm test
